#ifndef __NCMACHINEDEFINES_H
#define __NCMACHINEDEFINES_H

//#define CURRENT_AXIS_LEN 3
//#define AXIS_X 0
//#define AXIS_Y 1
//#define AXIS_Z 2

#define ALL_AXES "XYZU"

#define POS_AXIS_LEN 4	// 坐标显示
#define LOC_AXIS_LEN 4
#define SPK_AXIS_LEN 4
#define LJBC_AXIS_LEN 4	// 螺距补偿
#define POS_PAD_AXIS_LEN 4

#define ZEROAXIS_AXIS_LEN 3 // 坐标清零

#define SPK_CNO_SPECIAL 777 // 特殊的SPK CNo, 用于放电加工界面

#define POS_MEMORY_LEN 60

#define COMM0BASEADDR 0x0000
#define TCPIPBASEADDR 0x10000

#define TMBS_MAP0_ID_JOG_DUANLU (COMM0BASEADDR + 72)
#define TMBS_MAP0_ID_JOG_DUANLU_LEN 1


#define TMBS_MAP0_ID_XPOS (COMM0BASEADDR + 0)
#define TMBS_MAP0_ID_YPOS (COMM0BASEADDR + 1)
#define TMBS_MAP0_ID_ZPOS (COMM0BASEADDR + 2)
#define TMBS_MAP0_ID_UPOS (COMM0BASEADDR + 3)
#define TMBS_MAP0_ID_RSLT (COMM0BASEADDR + 4)
#define TMBS_MAP0_ID_NCTSTATE (COMM0BASEADDR + 5)
#define TMBS_MAP0_ID_SCAMANUL (COMM0BASEADDR + 6)
#define TMBS_MAP0_ID_INPUT (COMM0BASEADDR + 7)
#define TMBS_MAP0_ID_NCTCTR (COMM0BASEADDR + 8)
#define TMBS_MAP0_ID_JOGCFG (COMM0BASEADDR + 9)
#define TMBS_MAP0_ID_XJOGSPD (COMM0BASEADDR + 10)
#define TMBS_MAP0_ID_YJOGSPD (COMM0BASEADDR + 11)
#define TMBS_MAP0_ID_ZJOGSPD (COMM0BASEADDR + 12)
#define TMBS_MAP0_ID_UJOGSPD (COMM0BASEADDR + 13)
#define TMBS_MAP0_ID_CMVCFG (COMM0BASEADDR + 14)
#define TMBS_MAP0_ID_ORD (COMM0BASEADDR + 15)
#define TMBS_MAP0_ID_EXIT (COMM0BASEADDR + 16)

#define TMBS_MAP0_ID_KEY (COMM0BASEADDR + 17)
#define TMBS_MAP0_ID_HOPR (COMM0BASEADDR + 18)
#define TMBS_MAP0_ID_XOFST (COMM0BASEADDR + 19)
#define TMBS_MAP0_ID_YOFST (COMM0BASEADDR + 20)
#define TMBS_MAP0_ID_ZOFST (COMM0BASEADDR + 21)
#define TMBS_MAP0_ID_UOFST (COMM0BASEADDR + 22)
#define TMBS_MAP0_ID_MCUP (COMM0BASEADDR + 23)
#define TMBS_MAP0_ID_MCUSW (COMM0BASEADDR + 24)
#define TMBS_MAP0_ID_MCUCTRL (COMM0BASEADDR + 25)
#define TMBS_MAP0_ID_HCTRL (COMM0BASEADDR + 26)
#define TMBS_MAP0_ID_HSPD (COMM0BASEADDR + 27)
#define TMBS_MAP0_ID_HANDVER (COMM0BASEADDR + 28)
#define TMBS_MAP0_ID_DISPVER (COMM0BASEADDR + 29)
#define TMBS_MAP0_ID_XCPSPOPT (COMM0BASEADDR + 30)
#define TMBS_MAP0_ID_YCPSPOPT (COMM0BASEADDR + 31)
#define TMBS_MAP0_ID_ZCPSPOPT (COMM0BASEADDR + 32)
#define TMBS_MAP0_ID_UCPSPOPT (COMM0BASEADDR + 33)
#define TMBS_MAP0_ID_XGAP (COMM0BASEADDR + 34)
#define TMBS_MAP0_ID_YGAP (COMM0BASEADDR + 35)
#define TMBS_MAP0_ID_ZGAP (COMM0BASEADDR + 36)
#define TMBS_MAP0_ID_UGAP (COMM0BASEADDR + 37)
#define TMBS_MAP0_ID_XGAPMAXPT (COMM0BASEADDR + 38)
#define TMBS_MAP0_ID_YGAPMAXPT (COMM0BASEADDR + 39)
#define TMBS_MAP0_ID_ZGAPMAXPT (COMM0BASEADDR + 40)
#define TMBS_MAP0_ID_UGAPMAXPT (COMM0BASEADDR + 41)
#define TMBS_MAP0_ID_CPSPOPTCFG (COMM0BASEADDR + 42)
#define TMBS_MAP0_ID_CPSPOPTCFG_DISABLE (COMM0BASEADDR + 43)
#define TMBS_MAP0_ID_BJGJSJ (COMM0BASEADDR + 44)
#define TMBS_MAP0_ID_DJSNKZQ (COMM0BASEADDR + 45)
#define TMBS_MAP0_ID_FMQ (COMM0BASEADDR + 46)

#define TMBS_MAP0_ID_ADC (COMM0BASEADDR + 98)
#define TMBS_MAP0_ID_NCTSETTING (COMM0BASEADDR + 99)

#define TMBS_MAP0_ID_MAX 1000

#define TMBS_MAP0_ID_XPOS_LEN 2
#define TMBS_MAP0_ID_YPOS_LEN 2
#define TMBS_MAP0_ID_ZPOS_LEN 2
#define TMBS_MAP0_ID_UPOS_LEN 2
#define TMBS_MAP0_ID_RSLT_LEN 2
#define TMBS_MAP0_ID_NCTSTATE_LEN 1
#define TMBS_MAP0_ID_SCAMANUL_LEN 1
#define TMBS_MAP0_ID_INPUT_LEN 2
#define TMBS_MAP0_ID_NCTCTR_LEN 1
#define TMBS_MAP0_ID_JOGCFG_LEN 1
#define TMBS_MAP0_ID_XJOGSPD_LEN 2
#define TMBS_MAP0_ID_YJOGSPD_LEN 2
#define TMBS_MAP0_ID_ZJOGSPD_LEN 2
#define TMBS_MAP0_ID_UJOGSPD_LEN 2
#define TMBS_MAP0_ID_CMVCFG_LEN 4  // 3
#define TMBS_MAP0_ID_ORD_LEN 0
#define TMBS_MAP0_ID_EXIT_LEN 1


#define TMBS_MAP0_ID_KEY_LEN 4
#define TMBS_MAP0_ID_HOPR_LEN 3
#define TMBS_MAP0_ID_XOFST_LEN 2
#define TMBS_MAP0_ID_YOFST_LEN 2
#define TMBS_MAP0_ID_ZOFST_LEN 2
#define TMBS_MAP0_ID_UOFST_LEN 2
#define TMBS_MAP0_ID_MCUP_LEN 2
#define TMBS_MAP0_ID_MCUSW_LEN 1
#define TMBS_MAP0_ID_MCUCTRL_LEN 1
#define TMBS_MAP0_ID_HCTRL_LEN 1
#define TMBS_MAP0_ID_HSPD_LEN 1
#define TMBS_MAP0_ID_HANDVER_LEN 1
#define TMBS_MAP0_ID_DISPVER_LEN 1
#define TMBS_MAP0_ID_XCPSPOPT_LEN 6
#define TMBS_MAP0_ID_YCPSPOPT_LEN 6
#define TMBS_MAP0_ID_ZCPSPOPT_LEN 6
#define TMBS_MAP0_ID_UCPSPOPT_LEN 6
#define TMBS_MAP0_ID_XGAP_LEN 1
#define TMBS_MAP0_ID_YGAP_LEN 1
#define TMBS_MAP0_ID_ZGAP_LEN 1
#define TMBS_MAP0_ID_UGAP_LEN 1
#define TMBS_MAP0_ID_XGAPMAXPT_LEN 1
#define TMBS_MAP0_ID_YGAPMAXPT_LEN 1
#define TMBS_MAP0_ID_ZGAPMAXPT_LEN 1
#define TMBS_MAP0_ID_UGAPMAXPT_LEN 1
#define TMBS_MAP0_ID_CPSPOPTCFG_LEN 1
#define TMBS_MAP0_ID_BJGJSJ_LEN 2
#define TMBS_MAP0_ID_DJSNKZQ_LEN 1
#define TMBS_MAP0_ID_FMQ_LEN 4

#define TMBS_MAP0_ID_ADC_LEN 4
#define TMBS_MAP0_ID_NCTSETTING_LEN 4


// auto generate 
#define TMBS_MAP0_ID_ASDCS (COMM0BASEADDR + 47)
#define TMBS_MAP0_ID_CFDYSCBLXS (COMM0BASEADDR + 48)
#define TMBS_MAP0_ID_GOBLXS (COMM0BASEADDR + 49)
#define TMBS_MAP0_ID_FDHLXZCS (COMM0BASEADDR + 50)
#define TMBS_MAP0_ID_FDJGCFDY (COMM0BASEADDR + 51)
#define TMBS_MAP0_ID_JGMCSDSJ (COMM0BASEADDR + 52)
#define TMBS_MAP0_ID_FDCFGZCS (COMM0BASEADDR + 53)
#define TMBS_MAP0_ID_FDWCMS (COMM0BASEADDR + 54)
#define TMBS_MAP0_ID_FDDSSJ (COMM0BASEADDR + 55)
#define TMBS_MAP0_ID_TDFX (COMM0BASEADDR + 56)
#define TMBS_MAP0_ID_TDGD (COMM0BASEADDR + 57)
#define TMBS_MAP0_ID_TDSD (COMM0BASEADDR + 58)
#define TMBS_MAP0_ID_FDSJ (COMM0BASEADDR + 59)
#define TMBS_MAP0_ID_ECTDSJ (COMM0BASEADDR + 60)
#define TMBS_MAP0_ID_YDFX (COMM0BASEADDR + 61)
#define TMBS_MAP0_ID_ZDYDSD (COMM0BASEADDR + 62)
#define TMBS_MAP0_ID_SDJCXFS (COMM0BASEADDR + 63)
#define TMBS_MAP0_ID_YDFWXGCS (COMM0BASEADDR + 64)
#define TMBS_MAP0_ID_HZXTDPZSJ (COMM0BASEADDR + 65)
#define TMBS_MAP0_ID_ZTDJSSJ (COMM0BASEADDR + 66)
#define TMBS_MAP0_ID_TCQHTJL (COMM0BASEADDR + 67)
#define TMBS_MAP0_ID_TDQMSHTJL (COMM0BASEADDR + 68)
#define TMBS_MAP0_ID_TDQMSHTSD (COMM0BASEADDR + 69)

#define TMBS_MAP0_ID_HANDVER2 (COMM0BASEADDR + 73)
#define TMBS_MAP0_ID_YOUWENJIANCHE (COMM0BASEADDR + 74)
#define TMBS_MAP0_ID_YOUWEIJIANCHE (COMM0BASEADDR + 75)
#define TMBS_MAP0_ID_HUOYANJIANCHE (COMM0BASEADDR + 76)
#define TMBS_MAP0_ID_AJC (COMM0BASEADDR + 77)
#define TMBS_MAP0_ID_REG78 (COMM0BASEADDR + 78)
#define TMBS_MAP0_ID_REG79 (COMM0BASEADDR + 79)

#define TMBS_MAP0_ID_REG81 (COMM0BASEADDR + 81)

#define TMBS_MAP0_ID_REG83 (COMM0BASEADDR + 83)
#define TMBS_MAP0_ID_REG84 (COMM0BASEADDR + 84)
#define TMBS_MAP0_ID_REG85 (COMM0BASEADDR + 85)
#define TMBS_MAP0_ID_REG86 (COMM0BASEADDR + 86)

// TCP/IP modbus (connection 1)
#define TMBS_MAP1_ID_PLCSTATE (18)
//#define TMBS_MAP1_ID_PLCSTATE_LEN 3
#define TMBS_MAP1_ID_PLCOPERATION (TCPIPBASEADDR + 0)



#define TMBS_MAP0_ID_ASDCS_LEN 4
#define TMBS_MAP0_ID_CFDYSCBLXS_LEN 2
#define TMBS_MAP0_ID_GOBLXS_LEN 2
#define TMBS_MAP0_ID_FDHLXZCS_LEN 2
#define TMBS_MAP0_ID_FDJGCFDY_LEN 1
#define TMBS_MAP0_ID_JGMCSDSJ_LEN 6
#define TMBS_MAP0_ID_FDCFGZCS_LEN 2
#define TMBS_MAP0_ID_FDWCMS_LEN 1
#define TMBS_MAP0_ID_TCQHTJL_LEN 2
#define TMBS_MAP0_ID_FDDSSJ_LEN 2
#define TMBS_MAP0_ID_TDFX_LEN 1
#define TMBS_MAP0_ID_TDGD_LEN 2
#define TMBS_MAP0_ID_TDSD_LEN 1
#define TMBS_MAP0_ID_FDSJ_LEN 1
#define TMBS_MAP0_ID_ECTDSJ_LEN 2
#define TMBS_MAP0_ID_YDFX_LEN 1
#define TMBS_MAP0_ID_ZDYDSD_LEN 1
#define TMBS_MAP0_ID_SDJCXFS_LEN 1
#define TMBS_MAP0_ID_YDFWXGCS_LEN 4
#define TMBS_MAP0_ID_HZXTDPZSJ_LEN 4
#define TMBS_MAP0_ID_ZTDJSSJ_LEN 1
#define TMBS_MAP0_ID_TDQMSHTJL_LEN 2
#define TMBS_MAP0_ID_TDQMSHTSD_LEN 1

#define TMBS_MAP0_ID_HANDVER2_LEN 2
#define TMBS_MAP0_ID_YOUWENJIANCHE_LEN 1
#define TMBS_MAP0_ID_YOUWEIJIANCHE_LEN 1
#define TMBS_MAP0_ID_HUOYANJIANCHE_LEN 1

// end auto generate

#define NCT_STATE_API_RUN	0
#define NCT_STATE_JOG_RUN	(0 + 256)
#define NCT_STATE_JOG_EXIT	(1 + 256)
#define NCT_STATE_LOC_RUN	(0 + 512)
#define NCT_STATE_LOC_EXIT	(1 + 512)
#define NCT_STATE_CMV_RUN	(0 + 768)
#define NCT_STATE_CMV_EXIT	(1 + 768)
#define NCT_STATE_CMV_FINISHED	(2 + 768)
#define NCT_STATE_SPK_RUN	(0 + 1024)
#define NCT_STATE_SPK_EXTOC	(1 + 1024)
#define NCT_STATE_SPK_EXBAK	(2 + 1024)
#define NCT_STATE_SPK_PMBAK	(3 + 1024)
#define NCT_STATE_SPK_PMOV	(4 + 1024)
#define NCT_STATE_SPK_TOSPK	(5 + 1024)
#define NCT_STATE_INVALID	(-1)

#define TNC_ORDER0_JOG 0
#define TNC_ORDER0_LOC 1 
#define TNC_ORDER0_CMV 2
#define TNC_ORDER0_TOUCH 3
#define TNC_ORDER0_TOLMT 4
#define TNC_ORDER0_FRMLMT 5
#define TNC_ORDER0_TOZSIG 6
#define TNC_ORDER0_SPK 7
//#define TNC_ORDER0_SIZE 7


//-----------------------------------------------
#define KNLK_INVALID            0xFFFFFFFFFFFFFFFF             // 按下的按键为无效键
#define KNLK_NONE         	0                       		// 没有按键按下

#define KNLK_XSUB         	0x0000000000020000 	//X-
#define KNLK_XADD         	0x0002000000000000 	//X+
#define KNLK_YSUB         	0x0000000000000200 	//Y-
#define KNLK_YADD         	0x0000020000000000 //Y+
#define KNLK_ZSUB         	0x0000000000000002 //Z+
#define KNLK_ZADD         	0x0000000200000000 //Z-

#define KNLK_ASUB         	
#define KNLK_AADD         	
#define KNLK_BSUB         	
#define KNLK_BADD         	

#define KNLK_CENT         	0x0000000000000008 //对刀
#define KNLK_ST           	0x0000000400000000 //解除短路保护，JOG状态下，按下此按键，JOG移动忽略短路，无需上位机控制
#define KNLK_STEP         	0x0000000000000004 //点动移动

#define KNLK_SPEEDD       	0x0000000000080000 // SP-
#define KNLK_SPEEDU       	0x0008000000000000 // SP+

#define KNLK_PUMP1        	0x0000000000000800 //油泵1
#define KNLK_PUMP2        	0x0000080000000000 //油泵2

#define KNLK_START        	0x0000000800000000 //开始加工
#define KNLK_STOP         	0x0000000000000010 //停止加工

#define KNLK_ENT          	0x0000000000000080 //回车
#define KNLK_ESC          	0x0000000000000040 //返回
#endif

